const resources = {
	en: {
		translation: {
			home: "Home",
			feed: "Feed",
			NGOs: "NGOs",
			Donate: "Donate",
			Dashboard: "Dashboard",
			"My Tasks": "My Tasks",
			Profile: "Profile",
			Logout: "Logout",
			Login: "Login",
			Register: "Register",
			"Welcome Back": "Welcome Back",
			Email: "Email",
			Password: "Password",
			"Don't have an account?": "Don't have an account?",
			"Register here": "Register here",
			"Join ShareABite": "Join ShareABite",
			"Full Name": "Full Name",
			"Send OTP": "Send OTP",
			Verified: "Verified",
			"Enter OTP": "Enter OTP",
			"Verify OTP": "Verify OTP",
			"Confirm Password": "Confirm Password",
			"Register as": "Register as",
			Donor: "Donor",
			NGO: "NGO",
			Volunteer: "Volunteer",
			"Already have an account?": "Already have an account?",
			"Login here": "Login here",
		},
	},
	hi: {
		translation: {
			home: "होम",
			feed: "फ़ीड",
			NGOs: "एनजीओ",
			Donate: "दान करें",
			Dashboard: "डैशबोर्ड",
			"My Tasks": "मेरे कार्य",
			Profile: "प्रोफ़ाइल",
			Logout: "लॉग आउट",
			Login: "लॉग इन",
			Register: "रजिस्टर करें",
			"Welcome Back": "वापसी पर स्वागत है",
			Email: "ईमेल",
			Password: "पासवर्ड",
			"Don't have an account?": "क्या आपके पास खाता नहीं है?",
			"Register here": "यहाँ रजिस्टर करें",
			"Join ShareABite": "शेयरएबाइट में शामिल हों",
			"Full Name": "पूरा नाम",
			"Send OTP": "OTP भेजें",
			Verified: "सत्यापित",
			"Enter OTP": "OTP दर्ज करें",
			"Verify OTP": "OTP सत्यापित करें",
			"Confirm Password": "पासवर्ड की पुष्टि करें",
			"Register as": "के रूप में रजिस्टर करें",
			Donor: "दाता",
			NGO: "एनजीओ",
			Volunteer: "स्वयंसेवक",
			"Already have an account?": "क्या आपके पास पहले से एक खाता है?",
			"Login here": "यहाँ लॉग इन करें",
		},
	},
	mr: {
		translation: {
			home: "होम",
			feed: "फ़ीड",
			NGOs: "एनजीओ",
			Donate: "दान करा",
			Dashboard: "डॅशबोर्ड",
			"My Tasks": "माझे कार्य",
			Profile: "प्रोफाइल",
			Logout: "लॉग आउट",
			Login: "लॉग इन",
			Register: "रजिस्टर करा",
			"Welcome Back": "पुन्हा स्वागत आहे",
			Email: "ईमेल",
			Password: "पासवर्ड",
			"Don't have an account?": "खाते नहीं है?",
			"Register here": "यहां रजिस्टर करें",
			"Join ShareABite": "शेयरएबाइट में शामिल हों",
			"Full Name": "पूरा नाम",
			"Send OTP": "OTP भेजें",
			Verified: "सत्यापित",
			"Enter OTP": "OTP दर्ज करें",
			"Verify OTP": "OTP सत्यापित करें",
			"Confirm Password": "पासवर्ड की पुष्टि करें",
			"Register as": "के रूप में रजिस्टर करें",
			Donor: "दाता",
			NGO: "एनजीओ",
			Volunteer: "स्वयंसेवक",
			"Already have an account?": "क्या आपके पास पहले से एक खाता है?",
			"Login here": "यहां लॉग इन करें",
		},
	},
};
export default resources;
