const resources = {
	en: {
		translation: {
			home: "Home",
			feed: "Feed",
			NGOs: "NGOs",
			Donate: "Donate",
			Dashboard: "Dashboard",
			"My Tasks": "My Tasks",
			Profile: "Profile",
			Logout: "Logout",
			Login: "Login",
			Register: "Register",
			"Welcome Back": "Welcome Back",
			Email: "Email",
			Password: "Password",
			Status: "Status",
			"Don't have an account?": "Don't have an account?",
			"Register here": "Register here",
			"Join ShareABite": "Join ShareABite",
			"Full Name": "Full Name",
			"Send OTP": "Send OTP",
			Verified: "Verified",
			"Enter OTP": "Enter OTP",
			"Verify OTP": "Verify OTP",
			"Confirm Password": "Confirm Password",
			"Register as": "Register as",
			Donor: "Donor",
			NGO: "NGO",
			Volunteer: "Volunteer",
			"Already have an account?": "Already have an account?",
			"Login here": "Login here",
			"Only donors can create posts": "Only donors can create posts",
			"Donate Food": "Donate Food",
			"Upload Food Image": "Upload Food Image",
			"Click to upload food image": "Click to upload food image",
			"Choose Image": "Choose Image",
			"Donation Type": "Donation Type",
			"e.g., Food, Clothes, Books, Medicines":
				"e.g., Food, Clothes, Books, Medicines",
			Quantity: "Quantity",
			Meals: "Meals",
			"e.g., 5 meals, 10 kg, 20 books": "e.g., 5 meals, 10 kg, 20 books",
			"Expiry Time": "Expiry Time",
			"Estimated Beneficiaries": "Estimated Beneficiaries",
			"e.g., 50 people": "e.g., 50 people",
			"Select NGO": "Select NGO",
			"Assign to NGO": "Assign to NGO",
			"Pickup Location": "Pickup Location",
			"e.g., 123 Main St, City, Country":
				"e.g., 123 Main St, City, Country",
			"Use Current Location": "Use Current Location",
			"Submit Donation": "Submit Donation",
			"Auto-detected, you can edit": "Auto-detected, you can edit",
			"Enter manually": "Enter manually",
			Latitude: "Latitude",
			Longitude: "Longitude",
			Description: "Description",
			"Post Donation": "Post Donation",
			"Additional details about the food...":
				"Additional details about the food...",
			"Share Food, Share Hope": "Share Food, Share Hope",
			"Connect donors with NGOs to eliminate food waste and feed the hungry":
				"Connect donors with NGOs to eliminate food waste and feed the hungry",
			"Get Started": "Get Started",
			"Share your extra food with those in need. Every meal counts in fighting hunger.":
				"Share your extra food with those in need. Every meal counts in fighting hunger.",
			"Receive food donations and coordinate with volunteers for efficient distribution.":
				"Receive food donations and coordinate with volunteers for efficient distribution.",
			"Be the bridge between donors and NGOs. Help deliver hope to communities.":
				"Be the bridge between donors and NGOs. Help deliver hope to communities.",
			"For NGOs": "For NGOs",
			"For Donors": "For Donors",
			"For Volunteers": "For Volunteers",
			"Our Mission": "Our Mission",
			"FoodShare connects individuals and businesses with surplus food to NGOs and communities in need. We believe that no food should go to waste when there are people who need it.":
				"ShareABite connects individuals and businesses with surplus food to NGOs and communities in need. We believe that no food should go to waste when there are people who need it.",
			"Our platform makes it easy to donate, coordinate pickups through volunteers, and track the impact of your contributions. Together, we can build a world without hunger.":
				"Our platform makes it easy to donate, coordinate pickups through volunteers, and track the impact of your contributions. Together, we can build a world without hunger.",
			"Registered NGOs": "Registered NGOs",
			"No NGOs registered yet": "No NGOs registered yet",
			"View on Google Maps": "View on Google Maps",
			"NGO Dashboard": "NGO Dashboard",
			"No donations assigned yet": "No donations assigned yet",
			"Assign Volunteer": "Assign Volunteer",
			"Assigned to": "Assigned to",
			404: "404",
			"Oops! The page you are looking for does not exist.":
				"Oops! The page you are looking for does not exist.",
			"Go to Home": "Go to Home",
			"Donation Feed": "Donation Feed",
			"No donations posted yet": "No donations posted yet",
			"Post Your First Donation": "Post Your First Donation",
			"Donation Location": "Donation Location",
			"Open in Google Maps": "Open in Google Maps",
			"Please login to view profile": "Please login to view profile",
			"Save Changes": "Save Changes",
			"Edit Profile": "Edit Profile",
			Name: "Name",
			Phone: "Phone",
			"Auto-detected location (you can edit if needed)":
				"Auto-detected location (you can edit if needed)",
			"Unable to detect location. Please enter manually.":
				"Unable to detect location. Please enter manually.",
			"Organization Name": "Organization Name",
			"About Organization": "About Organization",
			Availability: "Availability",
			"No tasks assigned yet": "No tasks assigned yet",
			"Pickup Details": "Pickup Details",
			Location: "Location",
			"Delivery Details": "Delivery Details",
			"Update Status": "Update Status",
			"Picked Up": "Picked Up",
			Completed: "Completed",
			"Select Status": "Select Status",
			"Delivered to NGO": "Delivered to NGO",
			Cancel: "Cancel",
			Confirm: "Confirm",
			"Loading...": "Loading...",
			"Invalid credentials, please try again.":
				"Invalid credentials, please try again.",
			"Login failed. Please check your credentials or try again later.":
				"Login failed. Please check your credentials or try again later.",
			"Passwords do not match": "Passwords do not match",
			"Please enter a valid email": "Please enter a valid email",
			"OTP Sent Successfully": "OTP Sent Successfully",
			"Failed to send OTP. Please try again.":
				"Failed to send OTP. Please try again.",
			"OTP Verified!": "OTP Verified!",
			"Invalid OTP": "Invalid OTP",
			"Please verify your email first!":
				"Please verify your email first!",
			"Registration successful! Please login.":
				"Registration successful! Please login.",
			"Registration failed. Please try again.":
				"Registration failed. Please try again.",
			"Something went wrong. Please try again later.":
				"Something went wrong. Please try again later.",
			"Please upload an image.": "Please upload an image.",
			"Please provide a location.": "Please provide a location.",
			"Donation posted successfully!": "Donation posted successfully!",
			"Something went wrong while posting donation.":
				"Something went wrong while posting donation.",
			"Please select both post and volunteer":
				"Please select both post and volunteer",
			"Volunteer assigned successfully! Email notification sent.":
				"Volunteer assigned successfully! Email notification sent.",
			"Something went wrong!": "Something went wrong!",
			"Monthly Donation Analytics": "Monthly Donation Analytics",
			"User denied Geolocation": "User denied Geolocation",
			Pending: "Pending",
			Delivered: "Delivered",
			History: "History",
			Assigned: "Assigned",
			"My Donation History": "My Donation History",
			"Track all your donations and their status":
				"Track all your donations and their status",
		},
	},

	hi: {
		translation: {
			home: "होम",
			feed: "फ़ीड",
			NGOs: "एनजीओ",
			Donate: "दान करें",
			Dashboard: "डैशबोर्ड",
			"My Tasks": "मेरे कार्य",
			Profile: "प्रोफ़ाइल",
			Logout: "लॉग आउट",
			Login: "लॉग इन",
			Register: "रजिस्टर करें",
			"Welcome Back": "वापसी पर स्वागत है",
			Email: "ईमेल",
			Password: "पासवर्ड",
			Status: "स्थिति",
			"Don't have an account?": "क्या आपके पास खाता नहीं है?",
			"Register here": "यहाँ रजिस्टर करें",
			"Join ShareABite": "ShareABite से जुड़ें",
			"Full Name": "पूरा नाम",
			"Send OTP": "OTP भेजें",
			Verified: "सत्यापित",
			"Enter OTP": "OTP दर्ज करें",
			"Verify OTP": "OTP सत्यापित करें",
			"Confirm Password": "पासवर्ड की पुष्टि करें",
			"Register as": "के रूप में रजिस्टर करें",
			Donor: "दाता",
			NGO: "एनजीओ",
			Volunteer: "स्वयंसेवक",
			"Already have an account?": "क्या आपके पास पहले से खाता है?",
			"Login here": "यहाँ लॉग इन करें",
			"Only donors can create posts": "केवल दाता पोस्ट बना सकते हैं",
			"Donate Food": "भोजन दान करें",
			"Upload Food Image": "भोजन की तस्वीर अपलोड करें",
			"Click to upload food image":
				"भोजन की तस्वीर अपलोड करने के लिए क्लिक करें",
			"Choose Image": "तस्वीर चुनें",
			"Donation Type": "दान का प्रकार",
			"e.g., Food, Clothes, Books, Medicines":
				"जैसे: भोजन, कपड़े, किताबें, दवाइयाँ",
			Quantity: "मात्रा",
			Meals: "भोजन",
			"e.g., 5 meals, 10 kg, 20 books":
				"जैसे: 5 भोजन, 10 किलो, 20 किताबें",
			"Expiry Time": "समाप्ति समय",
			"Estimated Beneficiaries": "अनुमानित लाभार्थी",
			"e.g., 50 people": "जैसे: 50 लोग",
			"Select NGO": "एनजीओ चुनें",
			"Assign to NGO": "एनजीओ को सौंपें",
			"Pickup Location": "पिकअप स्थान",
			"e.g., 123 Main St, City, Country":
				"जैसे: 123 मुख्य सड़क, शहर, देश",
			"Use Current Location": "वर्तमान स्थान का उपयोग करें",
			"Submit Donation": "दान जमा करें",
			"Auto-detected, you can edit":
				"स्थान स्वतः पता चला (आप बदल सकते हैं)",
			"Enter manually": "मैन्युअली दर्ज करें",
			Latitude: "अक्षांश",
			Longitude: "देशांतर",
			Description: "विवरण",
			"Post Donation": "दान पोस्ट करें",
			"Additional details about the food...":
				"भोजन के बारे में अतिरिक्त जानकारी...",
			"Share Food, Share Hope": "भोजन बाँटें, आशा बाँटें",
			"Connect donors with NGOs to eliminate food waste and feed the hungry":
				"दानदाताओं को एनजीओ से जोड़कर खाद्य अपव्यय कम करें और भूखों को भोजन दें",
			"Get Started": "शुरू करें",
			"Share your extra food with those in need. Every meal counts in fighting hunger.":
				"अपना अतिरिक्त भोजन जरूरतमंदों के साथ साझा करें। हर भोजन मायने रखता है।",
			"Receive food donations and coordinate with volunteers for efficient distribution.":
				"भोजन दान प्राप्त करें और स्वयंसेवकों के साथ मिलकर वितरण करें",
			"Be the bridge between donors and NGOs. Help deliver hope to communities.":
				"दानदाताओं और एनजीओ के बीच सेतु बनें",
			"For NGOs": "एनजीओ के लिए",
			"For Donors": "दानदाताओं के लिए",
			"For Volunteers": "स्वयंसेवकों के लिए",
			"Our Mission": "हमारा मिशन",
			"FoodShare connects individuals and businesses with surplus food to NGOs and communities in need. We believe that no food should go to waste when there are people who need it.":
				"ShareABite अतिरिक्त भोजन को जरूरतमंदों तक पहुँचाता है",
			"Our platform makes it easy to donate, coordinate pickups through volunteers, and track the impact of your contributions. Together, we can build a world without hunger.":
				"हमारा प्लेटफॉर्म दान और वितरण को आसान बनाता है",
			"Registered NGOs": "पंजीकृत एनजीओ",
			"No NGOs registered yet": "अभी कोई एनजीओ पंजीकृत नहीं है",
			"View on Google Maps": "Google Maps पर देखें",
			"NGO Dashboard": "एनजीओ डैशबोर्ड",
			"No donations assigned yet": "अभी कोई दान असाइन नहीं हुआ",
			"Assign Volunteer": "स्वयंसेवक असाइन करें",
			"Assigned to": "सौंपा गया",
			404: "404",
			"Oops! The page you are looking for does not exist.":
				"यह पेज उपलब्ध नहीं है",
			"Go to Home": "होम पर जाएं",
			"Donation Feed": "दान सूची",
			"No donations posted yet": "अभी कोई दान पोस्ट नहीं हुआ",
			"Post Your First Donation": "पहला दान पोस्ट करें",
			"Donation Location": "दान स्थान",
			"Open in Google Maps": "Google Maps में खोलें",
			"Please login to view profile": "प्रोफ़ाइल देखने के लिए लॉगिन करें",
			"Save Changes": "परिवर्तन सहेजें",
			"Edit Profile": "प्रोफ़ाइल संपादित करें",
			Name: "नाम",
			Phone: "फोन",
			"Auto-detected location (you can edit if needed)":
				"स्थान स्वतः पता चला (आप चाहें तो बदल सकते हैं)",
			"Unable to detect location. Please enter manually.":
				"स्थान पता नहीं चल सका। कृपया दर्ज करें",
			"Organization Name": "संस्था का नाम",
			"About Organization": "संस्था के बारे में",
			Availability: "उपलब्धता",
			"No tasks assigned yet": "कोई कार्य नहीं मिला",
			"Pickup Details": "पिकअप विवरण",
			Location: "स्थान",
			"Delivery Details": "डिलीवरी विवरण",
			"Update Status": "स्थिति अपडेट करें",
			"Picked Up": "उठा लिया गया",
			Completed: "पूर्ण",
			"Select Status": "स्थिति चुनें",
			"Delivered to NGO": "एनजीओ को दिया गया",
			Cancel: "रद्द करें",
			Confirm: "पुष्टि करें",
			"Loading...": "लोड हो रहा है...",
			"Invalid credentials, please try again.":
				"गलत जानकारी, पुनः प्रयास करें",
			"Login failed. Please check your credentials or try again later.":
				"लॉगिन असफल",
			"Passwords do not match": "पासवर्ड मेल नहीं खा रहे",
			"Please enter a valid email": "सही ईमेल दर्ज करें",
			"OTP Sent Successfully": "OTP भेजा गया",
			"Failed to send OTP. Please try again.": "OTP भेजने में असफल",
			"OTP Verified!": "OTP सत्यापित",
			"Invalid OTP": "गलत OTP",
			"Please verify your email first!": "पहले ईमेल सत्यापित करें",
			"Registration successful! Please login.": "रजिस्ट्रेशन सफल",
			"Registration failed. Please try again.": "रजिस्ट्रेशन असफल",
			"Something went wrong. Please try again later.": "कुछ गलत हुआ",
			"Please upload an image.": "कृपया तस्वीर अपलोड करें",
			"Please provide a location.": "स्थान दर्ज करें",
			"Donation posted successfully!": "दान सफल",
			"Something went wrong while posting donation.":
				"दान पोस्ट करने में त्रुटि",
			"Please select both post and volunteer": "पोस्ट और स्वयंसेवक चुनें",
			"Volunteer assigned successfully! Email notification sent.":
				"स्वयंसेवक असाइन किया गया",
			"Something went wrong!": "कुछ गलत हुआ!",
			"Monthly Donation Analytics": "मासिक दान विश्लेषण",
			"User denied Geolocation": "उपयोगकर्ता ने जियोलोकेशन से इनकार किया",
			Pending: "लंबित",
			History: "इतिहास",
			Assigned: "सौंपा गया",
			"My Donation History": "माझे दान इतिहास",
			"Track all your donations and their status":
				"सभ्य दान आणि त्यांची स्थिती ट्रॅक करा",
			Delivered: "डिलीवर किया गया",
		},
	},

	mr: {
		translation: {
			home: "होम",
			feed: "फीड",
			NGOs: "एनजीओ",
			Donate: "दान करा",
			Dashboard: "डॅशबोर्ड",
			"My Tasks": "माझी कामे",
			Profile: "प्रोफाइल",
			Logout: "लॉग आउट",
			Login: "लॉग इन",
			Register: "नोंदणी करा",
			"Welcome Back": "पुन्हा स्वागत आहे",
			Email: "ईमेल",
			Password: "पासवर्ड",
			Status: "स्थिती",
			"Don't have an account?": "तुमच्याकडे खाते नाही का?",
			"Register here": "इथे नोंदणी करा",
			"Join ShareABite": "ShareABite मध्ये सामील व्हा",
			"Full Name": "पूर्ण नाव",
			"Send OTP": "OTP पाठवा",
			Verified: "सत्यापित",
			"Enter OTP": "OTP टाका",
			"Verify OTP": "OTP सत्यापित करा",
			"Confirm Password": "पासवर्डची पुष्टी करा",
			"Register as": "म्हणून नोंदणी करा",
			Donor: "दाता",
			NGO: "एनजीओ",
			Volunteer: "स्वयंसेवक",
			"Already have an account?": "आधीच खाते आहे का?",
			"Login here": "इथे लॉगिन करा",
			"Only donors can create posts": "फक्त दाते पोस्ट करू शकतात",
			"Donate Food": "अन्न दान करा",
			"Upload Food Image": "अन्नाचा फोटो अपलोड करा",
			"Click to upload food image": "फोटो अपलोड करण्यासाठी क्लिक करा",
			"Choose Image": "फोटो निवडा",
			"Donation Type": "दानाचा प्रकार",
			"e.g., Food, Clothes, Books, Medicines":
				"उदा., अन्न, कपडे, पुस्तके, औषधे",
			Quantity: "प्रमाण",
			Meals: "भोजन",
			"e.g., 5 meals, 10 kg, 20 books":
				"उदा., 5 भोजन, 10 किलो, 20 पुस्तके",
			"Expiry Time": "समाप्ती वेळ",
			"Estimated Beneficiaries": "अंदाजे लाभार्थी",
			"e.g., 50 people": "उदा., 50 लोक",
			"Select NGO": "एनजीओ निवडा",
			"Assign to NGO": "एनजीओला सोपवा",
			"Pickup Location": "पिकअप ठिकाण",
			"e.g., 123 Main St, City, Country":
				"उदा., 123 मुख्य रस्ता, शहर, देश",
			"Use Current Location": "सध्याचे स्थान वापरा",
			"Submit Donation": "दान सबमिट करा",
			"Auto-detected, you can edit":
				"स्थान आपोआप सापडले (तुम्ही बदल करू शकता)",
			"Enter manually": "स्वतः टाका",
			Latitude: "अक्षांश",
			Longitude: "रेखांश",
			Description: "वर्णन",
			"Post Donation": "दान पोस्ट करा",
			"Additional details about the food...": "अन्नाबद्दल अधिक माहिती...",
			"Share Food, Share Hope": "अन्न शेअर करा, आशा शेअर करा",
			"Connect donors with NGOs to eliminate food waste and feed the hungry":
				"दानदाते आणि एनजीओ यांना जोडून अन्न वाया जाणे टाळा",
			"Get Started": "सुरू करा",
			"Share your extra food with those in need. Every meal counts in fighting hunger.":
				"अतिरिक्त अन्न गरजूंना द्या",
			"Receive food donations and coordinate with volunteers for efficient distribution.":
				"दान गोळा करा आणि वितरण करा",
			"Be the bridge between donors and NGOs. Help deliver hope to communities.":
				"दानदाते आणि एनजीओ यांच्यात पूल बना",
			"For NGOs": "एनजीओसाठी",
			"For Donors": "दात्यांसाठी",
			"For Volunteers": "स्वयंसेवकांसाठी",
			"Our Mission": "आमचे ध्येय",
			"FoodShare connects individuals and businesses with surplus food to NGOs and communities in need. We believe that no food should go to waste when there are people who need it.":
				"ShareABite अतिरिक्त अन्न गरजूंना जोडतो",
			"Our platform makes it easy to donate, coordinate pickups through volunteers, and track the impact of your contributions. Together, we can build a world without hunger.":
				"आमचे प्लॅटफॉर्म दान करणे सोपे बनवते",
			"Registered NGOs": "नोंदणीकृत एनजीओ",
			"No NGOs registered yet": "अद्याप कोणतेही एनजीओ नाहीत",
			"View on Google Maps": "Google Maps वर पहा",
			"NGO Dashboard": "एनजीओ डॅशबोर्ड",
			"No donations assigned yet": "अजून कोणतेही दान नाही",
			"Assign Volunteer": "स्वयंसेवक निवडा",
			"Assigned to": "सोपवले",
			404: "404",
			"Oops! The page you are looking for does not exist.":
				"पेज सापडले नाही",
			"Go to Home": "होम वर जा",
			"Donation Feed": "दान यादी",
			"No donations posted yet": "अजून कोणतेही दान नाही",
			"Post Your First Donation": "पहिले दान पोस्ट करा",
			"Donation Location": "दान ठिकाण",
			"Open in Google Maps": "Google Maps मध्ये उघडा",
			"Please login to view profile": "प्रोफाइल पाहण्यासाठी लॉगिन करा",
			"Save Changes": "बदल जतन करा",
			"Edit Profile": "प्रोफाइल संपादित करा",
			Name: "नाव",
			Phone: "फोन",
			"Auto-detected location (you can edit if needed)":
				"स्थान आपोआप सापडले (तुम्ही बदल करू शकता)",
			"Unable to detect location. Please enter manually.":
				"स्थान सापडले नाही, कृपया टाका",
			"Organization Name": "संस्थेचे नाव",
			"About Organization": "संस्थेबद्दल",
			Availability: "उपलब्धता",
			"No tasks assigned yet": "कोणतीही कामे नाहीत",
			"Pickup Details": "पिकअप तपशील",
			Location: "स्थान",
			"Delivery Details": "डिलिव्हरी तपशील",
			"Update Status": "स्थिती अपडेट करा",
			"Picked Up": "उचलले",
			Completed: "पूर्ण",
			"Select Status": "स्थिती निवडा",
			"Delivered to NGO": "एनजीओला दिले",
			Cancel: "रद्द करा",
			Confirm: "पुष्टी करा",
			"Loading...": "लोड होत आहे...",
			"Invalid credentials, please try again.": "चुकीची माहिती",
			"Login failed. Please check your credentials or try again later.":
				"लॉगिन अयशस्वी",
			"Passwords do not match": "पासवर्ड जुळत नाहीत",
			"Please enter a valid email": "योग्य ईमेल टाका",
			"OTP Sent Successfully": "OTP पाठवला",
			"Failed to send OTP. Please try again.": "OTP पाठवण्यात अयशस्वी",
			"OTP Verified!": "OTP सत्यापित",
			"Invalid OTP": "चुकीचा OTP",
			"Please verify your email first!": "कृपया ईमेल सत्यापित करा",
			"Registration successful! Please login.": "नोंदणी यशस्वी",
			"Registration failed. Please try again.": "नोंदणी अयशस्वी",
			"Something went wrong. Please try again later.": "काहीतरी चूक झाली",
			"Please upload an image.": "फोटो अपलोड करा",
			"Please provide a location.": "स्थान द्या",
			"Donation posted successfully!": "दान यशस्वी",
			"Something went wrong while posting donation.":
				"दान पोस्ट करताना त्रुटी",
			"Please select both post and volunteer":
				"पोस्ट आणि स्वयंसेवक निवडा",
			"Volunteer assigned successfully! Email notification sent.":
				"स्वयंसेवक नेमला गेला",
			"Something went wrong!": "काहीतरी चूक झाली!",
			"Monthly Donation Analytics": "मासिक देणगी विश्लेषण",
			"User denied Geolocation": "वापरकर्त्याने भौगोलिक स्थान नाकारले",
			Pending: "प्रलंबित",
			History: "इतिहास",
			Assigned: "नियुक्त केले",
			"My Donation History": "माझे दान इतिहास",
			"Track all your donations and their status":
				"अपने सभी दान और उनकी स्थिति को ट्रैक करें",
			Delivered: "डिलीवर किया गया",
		},
	},
};

export default resources;

// const resources = {
// 	en: {
// 		translation: {
// 			home: "Home",
// 			feed: "Feed",
// 			NGOs: "NGOs",
// 			Donate: "Donate",
// 			Dashboard: "Dashboard",
// 			"My Tasks": "My Tasks",
// 			Profile: "Profile",
// 			Logout: "Logout",
// 			Login: "Login",
// 			Register: "Register",
// 			"Welcome Back": "Welcome Back",
// 			Email: "Email",
// 			Password: "Password",
// 			Status: "Status",
// 			"Don't have an account?": "Don't have an account?",
// 			"Register here": "Register here",
// 			"Join ShareABite": "Join ShareABite",
// 			"Full Name": "Full Name",
// 			"Send OTP": "Send OTP",
// 			Verified: "Verified",
// 			"Enter OTP": "Enter OTP",
// 			"Verify OTP": "Verify OTP",
// 			"Confirm Password": "Confirm Password",
// 			"Register as": "Register as",
// 			Donor: "Donor",
// 			NGO: "NGO",
// 			Volunteer: "Volunteer",
// 			"Already have an account?": "Already have an account?",
// 			"Login here": "Login here",
// 			"Only donors can create posts": "Only donors can create posts",
// 			"Donate Food": "Donate Food",
// 			"Upload Food Image": "Upload Food Image",
// 			"Click to upload food image": "Click to upload food image",
// 			"Choose Image": "Choose Image",
// 			"Donation Type": "Donation Type",
// 			"e.g., Food, Clothes, Books, Medicines":
// 				"e.g., Food, Clothes, Books, Medicines",
// 			Quantity: "Quantity",
// 			Meals: "Meals",
// 			"e.g., 5 meals, 10 kg, 20 books": "e.g., 5 meals, 10 kg, 20 books",
// 			"Expiry Time": "Expiry Time",
// 			"Estimated Beneficiaries": "Estimated Beneficiaries",
// 			"e.g., 50 people": "e.g., 50 people",
// 			"Select NGO": "Select NGO",
// 			"Assign to NGO": "Assign to NGO",
// 			"Pickup Location": "Pickup Location",
// 			"e.g., 123 Main St, City, Country":
// 				"e.g., 123 Main St, City, Country",
// 			"Use Current Location": "Use Current Location",
// 			"Submit Donation": "Submit Donation",
// 			"Auto-detected, you can edit": "Auto-detected, you can edit",
// 			"Enter manually": "Enter manually",
// 			Latitude: "Latitude",
// 			Longitude: "Longitude",
// 			Description: "Description",
// 			"Post Donation": "Post Donation",
// 			"Additional details about the food...":
// 				"Additional details about the food...",
// 			"Share Food, Share Hope": "Share Food, Share Hope",
// 			"Connect donors with NGOs to eliminate food waste and feed the hungry":
// 				"Connect donors with NGOs to eliminate food waste and feed the hungry",
// 			"Get Started": "Get Started",
// 			"Share your extra food with those in need. Every meal counts in fighting hunger.":
// 				"Share your extra food with those in need. Every meal counts in fighting hunger.",
// 			"Receive food donations and coordinate with volunteers for efficient distribution.":
// 				"Receive food donations and coordinate with volunteers for efficient distribution.",
// 			"Be the bridge between donors and NGOs. Help deliver hope to communities.":
// 				"Be the bridge between donors and NGOs. Help deliver hope to communities.",
// 			"For NGOs": "For NGOs",
// 			"For Donors": "For Donors",
// 			"For Volunteers": "For Volunteers",
// 			"Our Mission": "Our Mission",
// 			"FoodShare connects individuals and businesses with surplus food to NGOs and communities in need. We believe that no food should go to waste when there are people who need it.":
// 				"FoodShare connects individuals and businesses with surplus food to NGOs and communities in need. We believe that no food should go to waste when there are people who need it.",
// 			"Our platform makes it easy to donate, coordinate pickups through volunteers, and track the impact of your contributions. Together, we can build a world without hunger.":
// 				"Our platform makes it easy to donate, coordinate pickups through volunteers, and track the impact of your contributions. Together, we can build a world without hunger.",
// 			"Registered NGOs": "Registered NGOs",
// 			"No NGOs registered yet": "No NGOs registered yet",
// 			"View on Google Maps": "View on Google Maps",
// 			"NGO Dashboard": "NGO Dashboard",
// 			"No donations assigned yet": "No donations assigned yet",
// 			"Assign Volunteer": "Assign Volunteer",
// 			"Assigned to": "Assigned to",
// 			404: "404",
// 			"Oops! The page you are looking for does not exist.":
// 				"Oops! The page you are looking for does not exist.",
// 			"Go to Home": "Go to Home",
// 			"Food Donation Feed": "Food Donation Feed",
// 			"No donations posted yet": "No donations posted yet",
// 			"Post Your First Donation": "Post Your First Donation",
// 			"Donation Location": "Donation Location",
// 			"Open in Google Maps": "Open in Google Maps",
// 			"Please login to view profile": "Please login to view profile",
// 			"Save Changes": "Save Changes",
// 			"Edit Profile": "Edit Profile",
// 			Name: "Name",
// 			Phone: "Phone",
// 			"Auto-detected location (you can edit if needed)":
// 				"Auto-detected location (you can edit if needed)",
// 			"Unable to detect location. Please enter manually.":
// 				"Unable to detect location. Please enter manually.",
// 			"Organization Name": "Organization Name",
// 			"About Organization": "About Organization",
// 			Availability: "Availability",
// 			"No tasks assigned yet": "No tasks assigned yet",
// 			"Pickup Details": "Pickup Details",
// 			Location: "Location",
// 			"Delivery Details": "Delivery Details",
// 			"Update Status": "Update Status",
// 			"Picked Up": "Picked Up",
// 			Completed: "Completed",
// 			"Select Status": "Select Status",
// 			"Delivered to NGO": "Delivered to NGO",
// 			Cancel: "Cancel",
// 			Confirm: "Confirm",
// 			"Loading...": "Loading...",
// 			"Invalid credentials, please try again.":
// 				"Invalid credentials, please try again.",
// 			"Login failed. Please check your credentials or try again later.":
// 				"Login failed. Please check your credentials or try again later.",
// 			"Passwords do not match": "Passwords do not match",
// 			"Please enter a valid email": "Please enter a valid email",
// 			"OTP Sent Successfully": "OTP Sent Successfully",
// 			"Failed to send OTP. Please try again.":
// 				"Failed to send OTP. Please try again.",
// 			"OTP Verified!": "OTP Verified!",
// 			"Invalid OTP": "Invalid OTP",
// 			"Please verify your email first!":
// 				"Please verify your email first!",
// 			"Registration successful! Please login.":
// 				"Registration successful! Please login.",
// 			"Registration failed. Please try again.":
// 				"Registration failed. Please try again.",
// 			"Something went wrong. Please try again later.":
// 				"Something went wrong. Please try again later.",
// 			"Please upload an image.": "Please upload an image.",
// 			"Please provide a location.": "Please provide a location.",
// 			"Donation posted successfully!": "Donation posted successfully!",
// 			"Something went wrong while posting donation.":
// 				"Something went wrong while posting donation.",
//             "Please select both post and volunteer": "Please select both post and volunteer",
//             "Volunteer assigned successfully! Email notification sent.": "Volunteer assigned successfully! Email notification sent.",
//             "Something went wrong!": "Something went wrong!",
// 		},
// 	},
// 	//hindi
// 	hi: {
// 		translation: {
// 			home: "होम",
// 			feed: "फ़ीड",
// 			NGOs: "एनजीओ",
// 			Donate: "दान करें",
// 			Dashboard: "डैशबोर्ड",
// 			"My Tasks": "मेरे कार्य",
// 			Profile: "प्रोफ़ाइल",
// 			Logout: "लॉग आउट",
// 			Login: "लॉग इन",
// 			Register: "रजिस्टर करें",
// 			"Welcome Back": "वापसी पर स्वागत है",
// 			Email: "ईमेल",
// 			Password: "पासवर्ड",
// 			"Don't have an account?": "क्या आपके पास खाता नहीं है?",
// 			"Register here": "यहाँ रजिस्टर करें",
// 			"Join ShareABite": "शेयरएबाइट में शामिल हों",
// 			"Full Name": "पूरा नाम",
// 			"Send OTP": "OTP भेजें",
// 			Verified: "सत्यापित",
// 			"Enter OTP": "OTP दर्ज करें",
// 			"Verify OTP": "OTP सत्यापित करें",
// 			"Confirm Password": "पासवर्ड की पुष्टि करें",
// 			"Register as": "के रूप में रजिस्टर करें",
// 			Donor: "दाता",
// 			NGO: "एनजीओ",
// 			Volunteer: "स्वयंसेवक",
// 			"Already have an account?": "क्या आपके पास पहले से एक खाता है?",
// 			"Login here": "यहाँ लॉग इन करें",
// 			"Only donors can create posts": "केवल दाता पोस्ट बना सकते हैं",
// 			"Donate Food": "खाना दान करें",
// 			"Upload Food Image": "खाने की छवि अपलोड करें",
// 			"Click to upload food image":
// 				"खाने की छवि अपलोड करने के लिए क्लिक करें",
// 			"Choose Image": "छवि चुनें",
// 			"Donation Type": "दान का प्रकार",
// 			"e.g., Food, Clothes, Books, Medicines":
// 				"जैसे, खाना, कपड़े, किताबें, दवाइयाँ",
// 			Quantity: "मात्रा",
// 			"e.g., 5 meals, 10 kg, 20 books":
// 				"जैसे, 5 भोजन, 10 किलोग्राम, 20 किताबें",
// 			"Expiry Time": "समाप्ति समय",
// 			"Estimated Beneficiaries": "अनुमानित लाभार्थी",
// 			"e.g., 50 people": "जैसे, 50 लोग",
// 			"Select NGO": "एनजीओ चुनें",
// 			"Assign to NGO": "एनजीओ को असाइन करें",
// 			"Pickup Location": "पिकअप स्थान",
// 			"e.g., 123 Main St, City, Country":
// 				"जैसे, 123 मुख्य सड़क, शहर, देश",
// 			"Use Current Location": "वर्तमान स्थान का उपयोग करें",
// 			"Submit Donation": "दान जमा करें",
// 			"Auto-detected, you can edit":
// 				"स्वचालित रूप से पता लगाया गया, आप संपादित कर सकते हैं",
// 			"Enter manually": "मैन्युअल रूप से दर्ज करें",
// 			Latitude: "अक्षांश",
// 			Longitude: "देशांतर",
// 			Description: "विवरण",
// 			"Post Donation": "दान पोस्ट करें",
// 			"Additional details about the food...":
// 				"खाने के बारे में अतिरिक्त विवरण...",
// 			"Share Food, Share Hope": "खाना साझा करें, आशा साझा करें",
// 			"Connect donors with NGOs to eliminate food waste and feed the hungry":
// 				"दाताओं के एनजीओ के साथ जोड़ें ताकि खाद्य अपव्यय को रोका जा सके और भूखे लोगों को पोषण मिले",
// 			"Get Started": "शुरू करें",
// 			"Share your extra food with those in need. Every meal counts in fighting hunger.":
// 				"अपना अतिरिक्त खाना उन लोगों के साथ साझा करें जिन्हें इसकी आवश्यकता है। हर भोजन भूख से लड़ने में महत्वपूर्ण है।",
// 			"Receive food donations and coordinate with volunteers for efficient distribution.":
// 				"खाद्य दान प्राप्त करें और स्वयंसेवकों के साथ समन्वय करें ताकि कुशल वितरण हो सके।",
// 			"Be the bridge between donors and NGOs. Help deliver hope to communities.":
// 				"दाताओं और एनजीओ के बीच पुल बनें। समुदायों तक आशा पहुंचाने में मदद करें।",
// 			"For NGOs": "एनजीओ के लिए",
// 			"For Volunteers": "स्वयंसेवकों के लिए",
// 			"For Donors": "दाताओं के लिए",
// 			"Our Mission": "हमारा मिशन",
// 			"FoodShare connects individuals and businesses with surplus food to NGOs and communities in need. We believe that no food should go to waste when there are people who need it.":
// 				"फूडशेयर व्यक्तियों और व्यवसायों को अतिरिक्त भोजन के साथ एनजीओ और जरूरतमंद समुदायों से जोड़ता है। हमारा मानना है कि जब लोग भूखे हैं तो कोई भी भोजन बर्बाद नहीं होना चाहिए।",
// 			"Our platform makes it easy to donate, coordinate pickups through volunteers, and track the impact of your contributions. Together, we can build a world without hunger.":
// 				"हमारा प्लेटफ़ॉर्म दान करना, स्वयंसेवकों के माध्यम से पिकअप का समन्वय करना और आपके योगदान के प्रभाव को ट्रैक करना आसान बनाता है। साथ मिलकर, हम एक ऐसी दुनिया बना सकते हैं जिसमें भूख न हो।",
// 		},
// 	},
// 	//marathi
// 	mr: {
// 		translation: {
// 			home: "होम",
// 			feed: "फ़ीड",
// 			NGOs: "एनजीओ",
// 			Donate: "दान करा",
// 			Dashboard: "डॅशबोर्ड",
// 			"My Tasks": "माझे कार्य",
// 			Profile: "प्रोफाइल",
// 			Logout: "लॉग आउट",
// 			Login: "लॉग इन",
// 			Register: "रजिस्टर करा",
// 			"Welcome Back": "पुन्हा स्वागत आहे",
// 			Email: "ईमेल",
// 			Password: "पासवर्ड",
// 			"Don't have an account?": "खाते नहीं है?",
// 			"Register here": "यहां रजिस्टर करें",
// 			"Join ShareABite": "शेयरएबाइट में शामिल हों",
// 			"Full Name": "पूरा नाम",
// 			"Send OTP": "OTP भेजें",
// 			Verified: "सत्यापित",
// 			"Enter OTP": "OTP दर्ज करें",
// 			"Verify OTP": "OTP सत्यापित करें",
// 			"Confirm Password": "पासवर्ड की पुष्टि करें",
// 			"Register as": "के रूप में रजिस्टर करें",
// 			Donor: "दाता",
// 			NGO: "एनजीओ",
// 			Volunteer: "स्वयंसेवक",
// 			"Already have an account?": "क्या आपके पास पहले से एक खाता है?",
// 			"Login here": "यहां लॉग इन करें",
// 			"Only donors can create posts": "केवल दाता पोस्ट बना सकते हैं",
// 			"Donate Food": "खाना दान करें",
// 			"Upload Food Image": "खाने की छवि अपलोड करें",
// 			"Click to upload food image":
// 				"खाने की छवि अपलोड करने के लिए क्लिक करें",
// 			"Choose Image": "छवि चुनें",
// 			"Donation Type": "दान का प्रकार",
// 			"e.g., Food, Clothes, Books, Medicines":
// 				"जैसे, खाना, कपड़े, किताबें, दवाइयाँ",
// 			Quantity: "मात्रा",
// 			"e.g., 5 meals, 10 kg, 20 books":
// 				"जैसे, 5 भोजन, 10 किलोग्राम, 20 किताबें",
// 			"Expiry Time": "समाप्ति समय",
// 			"Estimated Beneficiaries": "अनुमानित लाभार्थी",
// 			"e.g., 50 people": "जैसे, 50 लोग",
// 			"Select NGO": "एनजीओ चुनें",
// 			"Assign to NGO": "एनजीओ को असाइन करें",
// 			"Pickup Location": "पिकअप स्थान",
// 			"e.g., 123 Main St, City, Country":
// 				"जैसे, 123 मुख्य सड़क, शहर, देश",
// 			"Use Current Location": "वर्तमान स्थान का उपयोग करें",
// 			"Submit Donation": "दान जमा करें",
// 			"Auto-detected, you can edit":
// 				"स्वचालित रूप से पता लगाया गया, आप संपादित कर सकते हैं",
// 			"Enter manually": "मैन्युअल रूप से दर्ज करें",
// 			Latitude: "अक्षांश",
// 			Longitude: "देशांतर",
// 			Description: "विवरण",
// 			"Post Donation": "दान पोस्ट करें",
// 			"Additional details about the food...":
// 				"खाने के बारे में अतिरिक्त विवरण...",
// 			"Share Food, Share Hope": "खाना साझा करें, आशा साझा करें",
// 		},
// 	},
// };
// export default resources;
