export const mockData: any = {
	users: [
		{
			id: 1,
			name: "John Doe",
			email: "john@example.com",
			role: "donor",
			location: "Pune",
		},
		{
			id: 2,
			name: "Helping Hands NGO",
			email: "help@ngo.com",
			role: "ngo",
			location: "Pune",
			contact: "helpinghands@ngo.com",
			phone: "9998887770",
			latitude: 18.5204,
			longitude: 73.8567,
			image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=100",
			organizationName: "",
			aboutOrganization: "",
		},
		{
			id: 3,
			name: "Alice Smith",
			email: "alice@example.com",
			role: "volunteer",
			location: "Mumbai",
		},
		{
			id: 4,
			name: "Bob Johnson",
			email: "bob@example.com",
			role: "volunteer",
			location: "Delhi",
		},
	],

	posts: [
		{
			id: 101,
			foodType: "Cooked Meals",
			quantity: "20 Boxes",
			meals: 100,
			description: "Vegetarian meals packed fresh",
			location: "Pune, Maharashtra",
			donorId: 1,
			assignedNGO: 2,
			status: "pending",
			image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600",
		},
		{
			id: 102,
			foodType: "Fruits",
			quantity: "50 kg",
			meals: 150,
			description: "Fresh seasonal fruits",
			location: "Pune, Maharashtra",
			donorId: 1,
			assignedNGO: 1,
			status: "pending",
			image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600",
		},
		{
			id: 103,
			foodType: "Vegetables",
			quantity: "30 kg",
			meals: 120,
			description: "Mixed fresh vegetables",
			location: "Mumbai, Maharashtra",
			donorId: 1,
			assignedNGO: 2,
			status: "assigned",
			image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
		},
	],
	assignments: [
		{
			id: 1001,
			postId: 103,
			volunteerId: 1,
			status: "assigned",
			assignedAt: new Date().toISOString(),
		},
	],
};
